default: &default
  adapter: postgresql
  encoding: unicode
  pool: 25
  username: postgres
  password: 				


development:
  <<: *default
  database: postgres

test:
  <<: *default

production:
  <<: *default